name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Install poetry 
        uses: abatilo/actions-poetry@v4
    
      - name: Config
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry config http-basic.pypi "${{ env.PYPI_USERNAME }}" "${{ env.PYPI_PASSWORD }}"

      - name: Build
        run: |
          poetry build

      - name: Publish
        run: |
          poetry publish